version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
     - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: /sbin/my_init -- bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
     - "3000:3000"
     - "3001:22" # ssh connections
    volumes:
     - .:/home/app/webapp
     - /var/lib/gems/2.2.0
     - /home/app/webapp/vendor/assets
    links:
      - database
      - redis
    environment:
      SERVICE: app
      ENV: ${ENV}
      PASSENGER_APP_ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_EXCEPTIONS_CHANNEL: ${SLACK_EXCEPTIONS_CHANNEL}
      TERM: xterm-256color
